source 'https://rubygems.org'

gem 'sinatra'
gem 'rack'
gem 'rackup'
gem 'puma'
gem 'json'
gem 'faraday'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'capybara'
  gem 'selenium-webdriver'
end
